export const productData = [
    { id: 'suitcase',
        name: 'Suitcase',
        image: '../assets/bag.jpg',
    },
    { id: 'banana-slicer',
        name: 'Banana Slicer',
        image: '../assets/banana.jpg',
    },
    { id: 'bathroom',
        name: 'iPad and Toilet Paper Holder',
        image: '../assets/bathroom.jpg',
    },
    { id: 'boots',
        name: 'Rain Boots',
        image: '../assets/boots.jpg',
    },
    { id: 'breakfast',
        name: 'All-In-One Breakfast Cooker',
        image: '../assets/breakfast.jpg',
    },
    { id: 'bubblegum',
        name: 'Meatball Bubblegum',
        image: '../assets/bubblegum.jpg',
    },
    { id: 'chair',
        name: 'Chair',
        image: '../assets/chair.jpg',
    },
    { id: 'alien',
        name: 'Toy Alien',
        image: '../assets/alien.jpg',
    },
    { id: 'dog-duck',
        name: 'Duck Bill for Dogs',
        image: '../assets/dog-duck.jpg',
    },
    { id: 'dragon',
        name: 'Dragon Meat',
        image: '../assets/dragon.jpg',
    },
    { id: 'pen',
        name: 'Plasticwear Pen Caps',
        image: '../assets/pen.jpg',
    },
    { id: 'pet-sweep',
        name: 'Pet Sweep',
        image: '../assets/pet-sweep.jpg',
    },
    { id: 'scissors',
        name: 'Pizza Scissors',
        image: '../assets/scissors.jpg',
    },
    { id: 'shark',
        name: 'Shark Pillow',
        image: '../assets/shark.jpg',
    },
    { id: 'baby-sweep',
        name: 'Baby Sweep',
        image: '../assets/baby-sweep.jpg',
    },
    { id: 'tuantuan',
        name: 'Tuantuan Sleeping Bag',
        image: '../assets/tuantuan.jpg',
    },
    { id: 'unicorn',
        name: 'Unicorn Meat',
        image: '../assets/unicorn.jpg',
    },
    { id: 'usb',
        name: 'Tail USB',
        image: '../assets/usb.jpg',
    },
    { id: 'water-can',
        name: 'Gag Watering Can',
        image: '../assets/water-can.jpg',
    },
    { id: 'wine-glass',
        name: 'Wine Glass',
        image: '../assets/wine-glass.jpg',
    },
];